// Compile test: every public and detail header of the core library is
// included by this translation unit. Per-header self-containment (each header
// compiling as the first include of a TU) cannot be expressed in a single TU;
// the include list below is sorted so that small leaf headers precede the
// aggregating ones, which catches most missing-include regressions.

#include "mdnspp/dns.h"
#include "mdnspp/parse.h"
#include "mdnspp/policy.h"
#include "mdnspp/records.h"
#include "mdnspp/defaults.h"
#include "mdnspp/dns_name.h"
#include "mdnspp/endpoint.h"
#include "mdnspp/mdns_error.h"
#include "mdnspp/cache_entry.h"
#include "mdnspp/mdns_options.h"
#include "mdnspp/record_cache.h"
#include "mdnspp/service_info.h"
#include "mdnspp/service_type.h"
#include "mdnspp/basic_querier.h"
#include "mdnspp/cache_options.h"
#include "mdnspp/query_options.h"
#include "mdnspp/basic_observer.h"
#include "mdnspp/callback_types.h"
#include "mdnspp/socket_options.h"
#include "mdnspp/basic_nic_group.h"
#include "mdnspp/monitor_options.h"
#include "mdnspp/service_options.h"
#include "mdnspp/observer_options.h"
#include "mdnspp/resolved_service.h"
#include "mdnspp/basic_nic_monitor.h"
#include "mdnspp/network_interface.h"
#include "mdnspp/nic_group_options.h"
#include "mdnspp/basic_service_server.h"
#include "mdnspp/basic_service_monitor.h"
#include "mdnspp/basic_service_discovery.h"

#include "mdnspp/default/default_timer.h"
#include "mdnspp/default/default_policy.h"
#include "mdnspp/default/default_socket.h"
#include "mdnspp/default/default_context.h"

#include "mdnspp/detail/compat.h"
#include "mdnspp/detail/dns_read.h"
#include "mdnspp/detail/dns_wire.h"
#include "mdnspp/detail/platform.h"
#include "mdnspp/detail/dns_enums.h"
#include "mdnspp/detail/dns_frame.h"
#include "mdnspp/detail/dns_query.h"
#include "mdnspp/detail/dns_write.h"
#include "mdnspp/detail/mdns_util.h"
#include "mdnspp/detail/recv_loop.h"
#include "mdnspp/detail/peer_traits.h"
#include "mdnspp/detail/ttl_refresh.h"
#include "mdnspp/detail/dns_response.h"
#include "mdnspp/detail/hash_combine.h"
#include "mdnspp/detail/query_backoff.h"
#include "mdnspp/detail/tc_accumulator.h"
#include "mdnspp/detail/server_validate.h"
#include "mdnspp/detail/server_query_match.h"
#include "mdnspp/detail/validate_multicast.h"
#include "mdnspp/detail/server_known_answer.h"
#include "mdnspp/detail/basic_mdns_peer_base.h"
#include "mdnspp/detail/nic_monitor_backends.h"
#include "mdnspp/detail/server_probe_announce.h"
#include "mdnspp/detail/server_response_aggregation.h"
#include "mdnspp/detail/duplicate_answer_suppression.h"

int main() {}
