name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y pkg-config

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config

      - name: Configure CMake
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            CMAKE_GENERATOR_OPTIONS="-A x64"
          fi
          
          cmake . -B build -DCMAKE_BUILD_TYPE=Release $CMAKE_GENERATOR_OPTIONS \
            -DMDNSPP_BUILD_TESTS=ON \
            -DMDNSPP_BUILD_EXAMPLES=ON

      - name: Build project
        run: cmake --build build --config Release

      - name: Test project
        run: |
          cd build
          ctest -C Release --output-on-failure